#https://stackoverflow.com/questions/63054846/aws-service-does-not-get-redeployed-how-to-fix-that
version: 2.1
orbs:  
  aws-ecr: circleci/aws-ecr@6.12.2 
  aws-ecs: circleci/aws-ecs@1.1.0
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: ACCESS_KEY_ID
          aws-secret-access-key: SECRET_ACCESS_KEY  
          repo: supermarketapi
          region: AWS_REGION 
          tag: latest 

      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          aws-access-key-id: ACCESS_KEY_ID
          aws-secret-access-key: SECRET_ACCESS_KEY
          family: ecs-task-1
          cluster-name: ecs-cluster-1
          service-name: ecs-service-1
          force-new-deployment: true
          container-image-name-updates: 'container=supermarketapi,tag=latest'